### ISSUE TITLE
Please add support for utf8-string 1.x

### ISSUE THREAD

**Issue by peti** [Andrey-Sisoyev/haskell-PCLT#1]
we would like to update NixOS to the latest version of `utf8-string`, but unfortunately your package doesn't compile against the new version. Is there any chance of getting a quick update to remedy that issue?

**Comment by Andrey-Sisoyev** [comment]
Hi Peter.
Unfortunately, I'm very far away from supporting this package. I'm not against if it's removed from Hackage.

**Comment by peti** [comment]
Hi Andrey, removing packages from Hackage hardly ever happens, I'm afraid, but it's very easy to mark it as "deprecated" at http://hackage.haskell.org/package/PCLT/maintain. Then people can see on the homepage that it's not maintained (and someone might even step up to take it over). The same applies to `PCLT-DB`, I belive, which depends on this package.

**Comment by Andrey-Sisoyev** [comment]
I changed statuses of both packages "deprecated".
I guess, issue is solved for you now?

**Comment by peti** [comment]
Yes, thank you very much for your help!
